# Generated by Django 5.0.2 on 2024-02-24 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'bilmirem',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('volumes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.volume')),
            ],
            options={
                'verbose_name_plural': 'Məqalə',
                'ordering': ['id'],
            },
        ),
    ]
