# Generated by Django 5.0.2 on 2024-02-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(default=0, upload_to='articles'),
            preserve_default=False,
        ),
    ]
