# Generated by Django 5.0.2 on 2024-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_article_volumes_article_volumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
