name: Deploy to Web Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{secrets.SSH_HOST}} > ~/.ssh/known_hosts

    - name: Deploy to Web Server
      run: |
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} 'cd /home/aisedaor/jurnal.aiseda.org.az && git checkout master && git pull && source ../virtualenv/jurnal.aiseda.org.az/3.11/bin/activate && pip install -r requirements.txt && python manage.py migrate && deactivate && systemctl daemon-reload && systemctl restart gunicorn && nginx -t && systemctl restart nginx'